import { SOCKET_URL } from '@/types';
import { getUUID } from '@/utils';
import { io, Socket } from 'socket.io-client';

/**
 * socket is a configured Socket.IO client instance for real-time communication.
 *
 * @description This instance of Socket.IO is set up to connect to the server specified by `SOCKET_URL`. It is configured with
 * specific options including transport method, reconnection behavior, and connection timeout. The `transports` option specifies
 * the use of WebSocket as the transport method. The client is set to attempt reconnections up to 5 times with a delay of 5 seconds
 * between attempts. The `timeout` option is set to 20 seconds to control the maximum time allowed for a connection attempt.
 * 
 * A unique UUID, generated by the `getUUID` utility function, is included in the query parameters for tracking or identifying
 * connections.
 *
 * @constant {Socket} socket - The configured Socket.IO client instance for real-time communication.
 *
 * @example
 * // Example usage of the socket instance
 * socket.on('connect', () => {
 *   console.log('Connected to the server');
 * });
 *
 * socket.on('message', (data) => {
 *   console.log('Received message:', data);
 * });
 *
 * socket.emit('event', { data: 'some data' });
 */
export const socket: Socket = io(SOCKET_URL, {
  transports: ['websocket'],
  reconnectionAttempts: 5,
  reconnectionDelay: 5000,
  timeout: 20000,
  query: {
    uuid: getUUID(),
  },
});
